"
Not Available, Not Attributed, Not Connected
"
Class {
	#name : 'PotsNARole',
	#superclass : 'PotsPinRole',
	#category : 'PharoThingsSimplified',
	#package : 'PharoThingsSimplified'
}

{ #category : 'accessing structure variables' }
PotsNARole class >> short [
	^'NA'
]

{ #category : 'as yet unclassified' }
PotsNARole >> deactivateOn: aPim [

]

{ #category : 'as yet unclassified' }
PotsNARole >> lastValue [ 
	^nil
]
